USE [master]
GO

/****** Object:  Database [CVs]    Script Date: 2021/05/25 01:00:23 ******/
CREATE DATABASE [CVs]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CVs', FILENAME = N'D:\MSSQL12.MSSQLSERVER\MSSQL\DATA\CVs.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CVs_log', FILENAME = N'D:\MSSQL12.MSSQLSERVER\MSSQL\DATA\CVs_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CVs].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CVs] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CVs] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CVs] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CVs] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CVs] SET ARITHABORT OFF 
GO

ALTER DATABASE [CVs] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CVs] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CVs] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CVs] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CVs] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CVs] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CVs] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CVs] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CVs] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CVs] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CVs] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CVs] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CVs] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CVs] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CVs] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CVs] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CVs] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CVs] SET RECOVERY FULL 
GO

ALTER DATABASE [CVs] SET  MULTI_USER 
GO

ALTER DATABASE [CVs] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CVs] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CVs] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CVs] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [CVs] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CVs] SET  READ_WRITE 
GO


